Document: ethminer-genoil
Title: Debian ethminer-genoil Manual
Author: <insert document author here>
Abstract: This manual describes what ethminer-genoil is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ethminer-genoil/ethminer-genoil.sgml.gz

Format: postscript
Files: /usr/share/doc/ethminer-genoil/ethminer-genoil.ps.gz

Format: text
Files: /usr/share/doc/ethminer-genoil/ethminer-genoil.text.gz

Format: HTML
Index: /usr/share/doc/ethminer-genoil/html/index.html
Files: /usr/share/doc/ethminer-genoil/html/*.html
